In [3]:
#Problem Statement : Hospital Patient Data Analysis
import pandas as pd
#Load patient dataset:
df = pd.read_csv("Patient_Data.csv")
df

,PatientID,Name,Department,Doctor,BillAmount,ReceptionistID,CheckInTime
0,101,Alice,Cardiology,Dr. Smith,5000.0,1,2023-01-10 09:00
1,102,Bob,Neurology,Dr. John,NaN,2,2023-01-11 10:30
2,103,Charlie,Orthopedics,Dr. Lee,7500.0,1,2023-01-12 11:00
3,104,David,Cardiology,Dr. Smith,6200.0,3,2023-01-13 12:00
4,105,Eva,Dermatology,Dr. Rose,NaN,2,2023-01-14 08:45
5,101,Alice,Cardiology,Dr. Smith,5000.0,1,2023-01-10 09:00

In [4]:
print(df.head())
df.info()

   PatientID     Name   Department     Doctor  BillAmount  ReceptionistID  \
0        101    Alice   Cardiology  Dr. Smith      5000.0               1
1        102      Bob    Neurology   Dr. John         NaN               2
2        103  Charlie  Orthopedics    Dr. Lee      7500.0               1
3        104    David   Cardiology  Dr. Smith      6200.0               3
4        105      Eva  Dermatology   Dr. Rose         NaN               2

        CheckInTime
0  2023-01-10 09:00
1  2023-01-11 10:30
2  2023-01-12 11:00
3  2023-01-13 12:00
4  2023-01-14 08:45
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   PatientID       6 non-null      int64
 1   Name            6 non-null      object
 2   Department      6 non-null      object
 3   Doctor          6 non-null      object
 4   BillAmount      4 non-null      float64
 5   ReceptionistID  6 non-null      int64
 6   CheckInTime     6 non-null      object
dtypes: float64(1), int64(2), object(4)
memory usage: 468.0+ bytes

In [5]:
billing_columns = df[['PatientID', 'Department', 'Doctor', 'BillAmount']]

print(billing_columns)

   PatientID   Department     Doctor  BillAmount
0        101   Cardiology  Dr. Smith      5000.0
1        102    Neurology   Dr. John         NaN
2        103  Orthopedics    Dr. Lee      7500.0
3        104   Cardiology  Dr. Smith      6200.0
4        105  Dermatology   Dr. Rose         NaN
5        101   Cardiology  Dr. Smith      5000.0

In [6]:
df = df.drop(['ReceptionistID', 'CheckInTime'], axis=1)

print(df)

   PatientID     Name   Department     Doctor  BillAmount
0        101    Alice   Cardiology  Dr. Smith      5000.0
1        102      Bob    Neurology   Dr. John         NaN
2        103  Charlie  Orthopedics    Dr. Lee      7500.0
3        104    David   Cardiology  Dr. Smith      6200.0
4        105      Eva  Dermatology   Dr. Rose         NaN
5        101    Alice   Cardiology  Dr. Smith      5000.0

In [8]:
total_bill = df.groupby('Department')['BillAmount'].sum()

print(total_bill)

Department
Cardiology     16200.0
Dermatology        0.0
Neurology          0.0
Orthopedics     7500.0
Name: BillAmount, dtype: float64

In [9]:
df = df.drop_duplicates(subset='PatientID')

print(df)

   PatientID     Name   Department     Doctor  BillAmount
0        101    Alice   Cardiology  Dr. Smith      5000.0
1        102      Bob    Neurology   Dr. John         NaN
2        103  Charlie  Orthopedics    Dr. Lee      7500.0
3        104    David   Cardiology  Dr. Smith      6200.0
4        105      Eva  Dermatology   Dr. Rose         NaN

In [10]:
mean_bill = df['BillAmount'].mean()

df['BillAmount'] = df['BillAmount'].fillna(mean_bill)

print(df)

   PatientID     Name   Department     Doctor   BillAmount
0        101    Alice   Cardiology  Dr. Smith  5000.000000
1        102      Bob    Neurology   Dr. John  6233.333333
2        103  Charlie  Orthopedics    Dr. Lee  7500.000000
3        104    David   Cardiology  Dr. Smith  6200.000000
4        105      Eva  Dermatology   Dr. Rose  6233.333333

In [12]:
#Loading the Billing Dataset:
billing_df = pd.read_csv("Billing_Data.csv")
billing_df

   PatientID  InsuranceCovered  FinalAmount
0        101              2000         3000
1        102              1500         3500
2        103              2500         5000
3        104              3000         3200
4        105              1000         4000

In [13]:
#Merging the two datasets:
merged_df = pd.merge(df, billing_df, on='PatientID')

print(merged_df)

   PatientID     Name   Department     Doctor   BillAmount  InsuranceCovered  \
0        101    Alice   Cardiology  Dr. Smith  5000.000000              2000
1        102      Bob    Neurology   Dr. John  6233.333333              1500
2        103  Charlie  Orthopedics    Dr. Lee  7500.000000              2500
3        104    David   Cardiology  Dr. Smith  6200.000000              3000
4        105      Eva  Dermatology   Dr. Rose  6233.333333              1000

   FinalAmount
0         3000
1         3500
2         5000
3         3200
4         4000

In [14]:
#Adding new patient rows:
new_patients = pd.DataFrame({
    'PatientID': [106, 107],
    'Name': ['John', 'Sara'],
    'Department': ['Cardiology', 'Neurology'],
    'Doctor': ['Dr. Smith', 'Dr. Kumar'],
    'BillAmount': [4000, 5000]
})

df = pd.concat([df, new_patients], ignore_index=True)

print(df)

   PatientID     Name   Department     Doctor   BillAmount
0        101    Alice   Cardiology  Dr. Smith  5000.000000
1        102      Bob    Neurology   Dr. John  6233.333333
2        103  Charlie  Orthopedics    Dr. Lee  7500.000000
3        104    David   Cardiology  Dr. Smith  6200.000000
4        105      Eva  Dermatology   Dr. Rose  6233.333333
5        106     John   Cardiology  Dr. Smith  4000.000000
6        107     Sara    Neurology  Dr. Kumar  5000.000000

In [15]:
#Adding new billing columns:
billing_categories = billing_df[['InsuranceCovered', 'FinalAmount']]

final_df = pd.concat([df, billing_categories], axis=1)

print(final_df)

   PatientID     Name   Department     Doctor   BillAmount  InsuranceCovered  \
0        101    Alice   Cardiology  Dr. Smith  5000.000000            2000.0
1        102      Bob    Neurology   Dr. John  6233.333333            1500.0
2        103  Charlie  Orthopedics    Dr. Lee  7500.000000            2500.0
3        104    David   Cardiology  Dr. Smith  6200.000000            3000.0
4        105      Eva  Dermatology   Dr. Rose  6233.333333            1000.0
5        106     John   Cardiology  Dr. Smith  4000.000000               NaN
6        107     Sara    Neurology  Dr. Kumar  5000.000000               NaN

   FinalAmount
0       3000.0
1       3500.0
2       5000.0
3       3200.0
4       4000.0
5          NaN
6          NaN