In [1]:
####1.Handle Missing Values:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [2]:
df=pd.read_csv('adult_with_headers (1).csv')

In [3]:
df

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
32557,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
32558,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
32559,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K
32560,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

In [4]:
df.head()

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [5]:
df.shape

(32561, 15)

In [6]:
df.size

488415

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             32561 non-null  int64
 1   workclass       32561 non-null  object
 2   fnlwgt          32561 non-null  int64
 3   education       32561 non-null  object
 4   education_num   32561 non-null  int64
 5   marital_status  32561 non-null  object
 6   occupation      32561 non-null  object
 7   relationship    32561 non-null  object
 8   race            32561 non-null  object
 9   sex             32561 non-null  object
 10  capital_gain    32561 non-null  int64
 11  capital_loss    32561 non-null  int64
 12  hours_per_week  32561 non-null  int64
 13  native_country  32561 non-null  object
 14  income          32561 non-null  object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB

In [8]:
df.describe()

,age,fnlwgt,education_num,capital_gain,capital_loss,hours_per_week
count,32561.000000,3.256100e+04,32561.000000,32561.000000,32561.000000,32561.000000
mean,38.581647,1.897784e+05,10.080679,1077.648844,87.303830,40.437456
std,13.640433,1.055500e+05,2.572720,7385.292085,402.960219,12.347429
min,17.000000,1.228500e+04,1.000000,0.000000,0.000000,1.000000
25%,28.000000,1.178270e+05,9.000000,0.000000,0.000000,40.000000
50%,37.000000,1.783560e+05,10.000000,0.000000,0.000000,40.000000
75%,48.000000,2.370510e+05,12.000000,0.000000,0.000000,45.000000
max,90.000000,1.484705e+06,16.000000,99999.000000,4356.000000,99.000000

In [9]:
df.isnull().sum()

age               0
workclass         0
fnlwgt            0
education         0
education_num     0
marital_status    0
occupation        0
relationship      0
race              0
sex               0
capital_gain      0
capital_loss      0
hours_per_week    0
native_country    0
income            0
dtype: int64

In [10]:
for col in df.columns:
    if df[col].dtype == 'object':
        df[col].fillna(df[col].mode()[0], inplace=True)
    else:
        df[col].fillna(df[col].mean(), inplace=True)

print(df.isnull().sum())

age               0
workclass         0
fnlwgt            0
education         0
education_num     0
marital_status    0
occupation        0
relationship      0
race              0
sex               0
capital_gain      0
capital_loss      0
hours_per_week    0
native_country    0
income            0
dtype: int64

In [11]:
###Separate Numerical Columns:
num_cols = df.select_dtypes(include=['int64', 'float64']).columns

In [12]:
num_cols

Index(['age', 'fnlwgt', 'education_num', 'capital_gain', 'capital_loss',
       'hours_per_week'],
      dtype='object')

In [13]:
#####Applying Scaling Techniques to Numerical Features:
##A.Standard Scaling:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
df_standard = df.copy()
df_standard[num_cols] = scaler.fit_transform(df_standard[num_cols])

In [14]:
df_standard[num_cols]

,age,fnlwgt,education_num,capital_gain,capital_loss,hours_per_week
0,0.030671,-1.063611,1.134739,0.148453,-0.21666,-0.035429
1,0.837109,-1.008707,1.134739,-0.145920,-0.21666,-2.222153
2,-0.042642,0.245079,-0.420060,-0.145920,-0.21666,-0.035429
3,1.057047,0.425801,-1.197459,-0.145920,-0.21666,-0.035429
4,-0.775768,1.408176,1.134739,-0.145920,-0.21666,-0.035429
...,...,...,...,...,...,...
32556,-0.849080,0.639741,0.746039,-0.145920,-0.21666,-0.197409
32557,0.103983,-0.335433,-0.420060,-0.145920,-0.21666,-0.035429
32558,1.423610,-0.358777,-0.420060,-0.145920,-0.21666,-0.035429
32559,-1.215643,0.110960,-0.420060,-0.145920,-0.21666,-1.655225
32560,0.983734,0.929893,-0.420060,1.888424,-0.21666,-0.035429

In [15]:
df_standard[num_cols].head()

,age,fnlwgt,education_num,capital_gain,capital_loss,hours_per_week
0,0.030671,-1.063611,1.134739,0.148453,-0.21666,-0.035429
1,0.837109,-1.008707,1.134739,-0.145920,-0.21666,-2.222153
2,-0.042642,0.245079,-0.420060,-0.145920,-0.21666,-0.035429
3,1.057047,0.425801,-1.197459,-0.145920,-0.21666,-0.035429
4,-0.775768,1.408176,1.134739,-0.145920,-0.21666,-0.035429

In [16]:
####B.Min-Max Scaling:
from sklearn.preprocessing import MinMaxScaler

mmscaler = MinMaxScaler()
df_minmax = df.copy()
df_minmax[num_cols] = mmscaler.fit_transform(df_minmax[num_cols])

In [17]:
df_minmax[num_cols]

,age,fnlwgt,education_num,capital_gain,capital_loss,hours_per_week
0,0.301370,0.044302,0.800000,0.021740,0.0,0.397959
1,0.452055,0.048238,0.800000,0.000000,0.0,0.122449
2,0.287671,0.138113,0.533333,0.000000,0.0,0.397959
3,0.493151,0.151068,0.400000,0.000000,0.0,0.397959
4,0.150685,0.221488,0.800000,0.000000,0.0,0.397959
...,...,...,...,...,...,...
32556,0.136986,0.166404,0.733333,0.000000,0.0,0.377551
32557,0.315068,0.096500,0.533333,0.000000,0.0,0.397959
32558,0.561644,0.094827,0.533333,0.000000,0.0,0.397959
32559,0.068493,0.128499,0.533333,0.000000,0.0,0.193878
32560,0.479452,0.187203,0.533333,0.150242,0.0,0.397959

In [18]:
df_minmax[num_cols].head()

,age,fnlwgt,education_num,capital_gain,capital_loss,hours_per_week
0,0.301370,0.044302,0.800000,0.02174,0.0,0.397959
1,0.452055,0.048238,0.800000,0.00000,0.0,0.122449
2,0.287671,0.138113,0.533333,0.00000,0.0,0.397959
3,0.493151,0.151068,0.400000,0.00000,0.0,0.397959
4,0.150685,0.221488,0.800000,0.00000,0.0,0.397959

## The scenarios where each scaling technique is preferred and why:
   
   Standard Scaling:
     * Best for algorithms like Logistic Regression, SVM, KNN, PCA.
     * Works well when data is approximately normally distributed.
   
   
   
   Min-Max Scaling:
     * Best for Neural Networks and distance-based methods when a fixed range is preferred.
     * Sensitive to outliers.

In [19]:
####2.Encoding Techniques:
######●	Apply One-Hot Encoding to categorical variables less than 5:
cat_cols = df.select_dtypes(include=['object']).columns

In [20]:
cat_cols

Index(['workclass', 'education', 'marital_status', 'occupation',
       'relationship', 'race', 'sex', 'native_country', 'income'],
      dtype='object')

In [21]:
small_cat = [col for col in cat_cols if df[col].nunique() < 5]
small_cat

['sex', 'income']

In [22]:
df_onehot = pd.get_dummies(df, columns=small_cat,drop_first=True)
df_onehot

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,capital_gain,capital_loss,hours_per_week,native_country,sex_ Male,income_ >50K
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,2174,0,40,United-States,True,False
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,0,0,13,United-States,True,False
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,0,0,40,United-States,True,False
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,0,0,40,United-States,True,False
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,0,0,40,Cuba,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,0,0,38,United-States,False,False
32557,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,0,0,40,United-States,True,True
32558,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,0,0,40,United-States,False,False
32559,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,0,0,20,United-States,True,False
32560,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,15024,0,40,United-States,False,True

In [23]:
df_onehot.head()

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,capital_gain,capital_loss,hours_per_week,native_country,sex_ Male,income_ >50K
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,2174,0,40,United-States,True,False
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,0,0,13,United-States,True,False
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,0,0,40,United-States,True,False
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,0,0,40,United-States,True,False
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,0,0,40,Cuba,False,False

In [24]:
####● Use Label Encoding for categorical variables:(more than 5 categories)
from sklearn.preprocessing import LabelEncoder

df_label = df.copy()
le = LabelEncoder()
large_cat = [col for col in cat_cols if df[col].nunique() >= 5]
for col in large_cat:
    df_label[col] = le.fit_transform(df_label[col])

In [25]:
(df_label[large_cat].head())

,workclass,education,marital_status,occupation,relationship,race,native_country
0,7,9,4,1,1,4,39
1,6,9,2,4,0,4,39
2,4,11,0,6,1,4,39
3,4,1,2,6,0,2,39
4,4,9,2,10,5,2,5

##  pros and cons of One-Hot Encoding and Label Encoding:
  
 #### One-Hot Encoding:
         Pros:
            No ordinal relationship is created.
            Good for low-cardinality categorical variables.
         Cons:
            Creates many new columns.
 #### Label Encoding:
         Pros:
             Simple and memory efficient.
             Useful for tree-based models.
         Cons:
             May create a false order among categories.

In [26]:
#####3.Feature Engineering:
 ####Creating 2 new Features:

In [27]:
# Feature 1: Age group
df['age_group'] = pd.cut(df['age'],
                         bins=[0, 25, 45, 65, 100],
                         labels=['Young', 'Adult', 'Middle', 'Senior'])
df[['age', 'age_group']]

       age age_group
0       39     Adult
1       50    Middle
2       38     Adult
3       53    Middle
4       28     Adult
...    ...       ...
32556   27     Adult
32557   40     Adult
32558   58    Middle
32559   22     Young
32560   52    Middle

[32561 rows x 2 columns]

In [28]:
df[['age', 'age_group']].head()

   age age_group
0   39     Adult
1   50    Middle
2   38     Adult
3   53    Middle
4   28     Adult

In [29]:
# Feature 2: Hours category
df['work_hours_type'] = np.where(df['hours_per_week'] >= 40,
                                 'Full-time',
                                 'Part-time')
df[['hours_per_week','work_hours_type']]

       hours_per_week work_hours_type
0                  40       Full-time
1                  13       Part-time
2                  40       Full-time
3                  40       Full-time
4                  40       Full-time
...               ...             ...
32556              38       Part-time
32557              40       Full-time
32558              40       Full-time
32559              20       Part-time
32560              40       Full-time

[32561 rows x 2 columns]

In [30]:
df[['hours_per_week','work_hours_type']].head()

   hours_per_week work_hours_type
0              40       Full-time
1              13       Part-time
2              40       Full-time
3              40       Full-time
4              40       Full-time

## Rationale of choosing Two New Features:

        Two new categorical features were created to improve the predictive power of the model. age_group represents different life stages, while work_hours_type represents employment intensity (full-time or part-time). These engineered features help the model identify meaningful patterns related to income and may improve classification performance.

In [31]:
####●Applying a transformation to atleast one skewed numerical feature:
df['capital_gain_log'] = np.log1p(df['capital_gain'])

In [32]:
df[['capital_gain', 'capital_gain_log']]

       capital_gain  capital_gain_log
0              2174          7.684784
1                 0          0.000000
2                 0          0.000000
3                 0          0.000000
4                 0          0.000000
...             ...               ...
32556             0          0.000000
32557             0          0.000000
32558             0          0.000000
32559             0          0.000000
32560         15024          9.617471

[32561 rows x 2 columns]

In [33]:
df[['capital_gain', 'capital_gain_log']].head()

   capital_gain  capital_gain_log
0          2174          7.684784
1             0          0.000000
2             0          0.000000
3             0          0.000000
4             0          0.000000

In [34]:
#Saving the final dataset:
df.to_csv('adult_preprocessed.csv', index=False)

In [35]:
print('Preprocessed dataset saved successfully')

Preprocessed dataset saved successfully

## Justification:
      Two new features, age_group and work_hours_type, were created to capture life-stage and employment-intensity information that may influence income. Additionally, a log transformation was applied to capital_gain to reduce skewness and the impact of extreme values, resulting in a more balanced feature distribution for machine learning models.”

## Conclusion:
The dataset was successfully preprocessed through missing-value handling, scaling, encoding, feature engineering, and transformation. The final dataset is cleaner and more suitable for building machine learning models.